CREATE DATABASE Base_Teste
ON (NAME = 'base_de_dados_teste.DAT',
        FILENAME = 'C:\TEMP\base_de_dados_teste.MDF',
        SIZE = 10MB,
        MAXSIZE = 50MB,
        FILEGROWTH = 5MB)

DROP DATABASE SUCOS_VENDAS_2;

CREATE TABLE [TABELA DE CLIENTES](
	[CPF] [CHAR] (11),
	[NOME] [VARCHAR] (150),
	[RUA] [VARCHAR] (150),
	[COMPLEMENTO] [VARCHAR] (150),
	[BAIRRO] [VARCHAR] (150),
	[ESTADO] [CHAR] (2),
	[CEP] [CHAR] (8),
	[DATA DE NASCIMENTO] [DATE],
	[IDADE] [SMALLINT],
	[SEXO] [CHAR] (1),
	[LIMITE DE CREDITO] [MONEY],
	[VOLUME MINIMO] [FLOAT],
	[PRIMEIRA COMPRA] [BIT]
)

ALTER TABLE [TABELA DE CLIENTES] ALTER COLUMN [CPF] [CHAR] (11) NOT NULL;

ALTER TABLE [TABELA DE CLIENTES] ADD CONSTRAINT PK_TABELA_CLIENTE
PRIMARY KEY CLUSTERED ([CPF]);

CREATE TABLE [TABELA DE VENDEDORES]
( [MATRICULA] varchar(5) NOT NULL PRIMARY KEY,
  [NOME] varchar(100),
  [PERCENTUAL COMISSAO] float);

INSERT INTO [TABELA DE PRODUTOS] VALUES (
'1040107',
'Light 350 ml - Melancia',
'Lata',
'350 ml',
'Melancia',
4.56
);

INSERT INTO [TABELA DE PRODUTOS] VALUES
('1037797', 'Clean 2 Litros Laranja', 'PET', '2 Litros', 'Laranja', 16.01);

INSERT INTO [TABELA DE PRODUTOS] VALUES
('1000889', 'Sabor da Montanha 700 ml Uva', 'Garrafa', '700 ml', 'Uva', 6.31);

INSERT INTO [TABELA DE PRODUTOS] VALUES
('1004327', 'Videira do Campo - 1,5 Litros Melancia', 'PET', '1,5 Litros', 'Melancia', 19.51);

INSERT INTO [TABELA DE PRODUTOS] VALUES
('1088126', 'Linha Citrus 1 Litro Limão', 'PET', '1 Litro', 'Limão', 7.00);

INSERT INTO [TABELA DE PRODUTOS] VALUES
('10837797', 'Clean - 2 Litros - Laranja', 'PET', '2 Litros', 'Laranja', 16.01), (1000889, Sabor da Montanha 700 ml Uva', 'Garrafa', 700 ml, 'Uva', 6.31),
('1004327, 'Videira do Campo 1,5 Litros Melancia', 'PET', '1,5 Litros', 'Melancia', 19.51),
(1088126', 'Linha Citrus 1 Litro Limão', 'PET', '1 Litro', 'Limão',7.00);

INSERT INTO [TABELA DE CLIENTES] VALUES
('00384393431', 'João da Silva', 'Rua Projetada A', 'Número 233', 'Copacabana', 'RJ', '20000000', '1965-03-21', 57, 'M', 20000000, 3000.30, 1),
('00384393555', 'Maria Clara', 'Rua Projetada A', 'Número 233', 'Copacabana', 'RJ', '20000000', '1975-03-21',47, 'F', 200000, 3000.30, 0);


INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00236','Cláudia Morais',0.08),
('00237','Marcela Ferreira',0.09),
('00238','Márcio Almeida',0.08);

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [PRECO DE LISTA], [SABOR])
VALUES
('5449310', 'Frescor do Verão - 350 ml - Limão', 'Lata', '350 ml',2.45, 'Limão'),
('1078680', 'Frescor do Verão - 350 ml - Manga', 'Lata', '350 ml',3.18, 'Manga');

SELECT [MATRICULA] AS IDENTIFICADOR,
               [NOME] AS [NOME DO VENDEDOR]
FROM [TABELA DE VENDEDORES];

SELECT [NOME], [DATA DE NASCIMENTO] 
FROM [TABELA DE CLIENTES]
WHERE [DATA DE NASCIMENTO] > '1995-12-31'


SELECT [NOME], [DATA DE NASCIMENTO] 
FROM [TABELA DE CLIENTES]
WHERE YEAR([DATA DE NASCIMENTO]) > '1995'

SELECT [NOME], [ESTADO], [PRIMEIRA COMPRA] 
FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = '1' AND [ESTADO] = 'SP';

SELECT * FROM [TABELA DE VENDEDORES] 
WHERE [PERCENTUAL COMISSAO] <= 0.08;

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [PRECO DE LISTA] < 6 AND EMBALAGEM = 'LATA';

SELECT * FROM [TABELA DE CLIENTES] 
WHERE NOT([ESTADO] = 'SP' OR [ESTADO] = 'RJ');

UPDATE [TABELA DE PRODUTOS] 
SET [PRECO DE LISTA] = [PRECO DE LISTA] * 0.9

UPDATE [TABELA DE PRODUTOS] 
SET [PRECO DE LISTA] = [PRECO DE LISTA] * 0.9
WHERE [EMBALAGEM] = 'Lata';

UPDATE [TABELA DE PRODUTOS] 
SET [EMBALAGEM] = 'Garrafa', [PRECO DE LISTA] = 8.10
WHERE [CODIGO DO PRODUTO] = '1088126';